const data = {
    products:[
        {
            _id: '1',
            name:'Onion Pallari',
            category: 'Vegetables',
            image: '/images/p1.jpg',
            price: 25,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: 'Good Quality Product',
        },
        {
            _id: '2',
            name:'Tomato',
            category: 'Vegetables',
            image: '/images/p2.jpg',
            price: 15,
            countInStock: 20,
            rating: 4.0,
            numReviews: 15,
            description: 'Good Quality Product',
        },
        {
            _id: '3',
            name:'Potato',
            category: 'Vegetables',
            image: '/images/p3.jpg',
            price: 20,
            countInStock: 25,
            rating: 4.5,
            numReviews: 20,
            description: 'Good Quality Product',
        },
        {
            _id: '4',
            name:'Cabbage',
            category: 'Vegetables',
            image: '/images/p4.jpg',
            price: 15,
            countInStock: 15,
            rating: 4.5,
            numReviews: 7,
            description: 'Good Quality Product',
        },
        {
            _id: '5',
            name:'Ladies Finger',
            category: 'Vegetables',
            image: '/images/p5.jpg',
            price: 18,
            countInStock: 0,
            rating: 4.8,
            numReviews: 2,
            description: 'Good Quality Product',
        },
        {
            _id: '6',
            name:'Carrot',
            category: 'Vegetables',
            image: '/images/p6.jpg',
            price: 30,
            countInStock: 20,
            rating: 4.5,
            numReviews: 14,
            description: 'Good Quality Product',
        },
    ],
};

export default data;